### ISSUE TITLE
update canvas when ctrl.data changes

### ISSUE THREAD

**Issue by melliott03** [christianascone/angular-points-path#3]
I want to be able to update the canvas when data is updated from the database. Is there a way to do this currently?

I'm using the generateRandomData() function to create the correct number of circles I need. That works fine. I've tried calling generateRandomData() again when the number of circles I need on the canvas changes in order to update ctrl.data but it doesn't update the canvas.

**Comment by melliott03** [comment]
I came with a solution to solve this problem.

**Comment by christianascone** [comment]
@melliott03 Sorry for being late. I started this project for academic purpose and I wasn't able to work on it for a few months. I'm happy to see you already solved the problem and I hope you found this repo useful
